### ISSUE TITLE
move var.rpr from model.R to model_parameters and change var.rpr to proportion.successful.recuits

### ISSUE THREAD

**Issue by cbird808** [population-genetic-modeling-dis/space_invaders#6]

**Comment by cbird808** [comment]
do this by leaving
var.rpr<-seq(0.25,1,length.out=4)
in model.R. But set variables A, B, C in model_parameters.R and modify model.R to be
initial.females <- var.rpr<-seq(A,B,length.out=C)

**Comment by mfrench1** [comment]
I have renamed var.rpr to proportion.successful.recruits and added variables (min_prop/max_prop, min_f_number/max_f_number, prop_increment/f_increment) to the parameters file.

proportion.successful.recuits<-seq(min_prop,max_prop,length.out=prop_increment)
initial.females <- seq(min_f_numer,max_f_number,length.out=f_increment)
